In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('/content/drive/MyDrive/innerwave/연습/data/student-mat.csv')
df

    school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0       GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1       GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2       GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3       GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4       GP   F   16       U     GT3       T  ...     2       5        4   6  10  10
..     ...  ..  ...     ...     ...     ...  ...   ...     ...      ...  ..  ..  ..
390     MS   M   20       U     LE3       A  ...     5       4       11   9   9   9
391     MS   M   17       U     LE3       T  ...     4       2        3  14  16  16
392     MS   M   21       R     GT3       T  ...     3       3        3  10   8   7
393     MS   M   18       R     LE3       T  ...     4       5        0  11  12  10
394     MS   M   19       U     LE3       T  ...     3       5        5   8   9   9

[395 rows x 33 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB

In [5]:
df['school'] = df['school'].replace({'GP':0, 'MS':1}).astype('category')

In [6]:
df['sex'] = df['sex'].replace({'F':0, 'M':1}).astype('category')

In [7]:
df['address'] = df['address'].replace({'U':0, 'R':1}).astype('category')

In [8]:
df['famsize'] = df['famsize'].replace({'GT3':0, 'LE3':1}).astype('category')

In [9]:
df['Pstatus'] = df['Pstatus'].replace({'A':0, 'T':1}).astype('category')

In [10]:
df[['Medu', 'Fedu']] = df[['Medu', 'Fedu']].astype('category')

In [11]:
df['Mjob'] = df['Mjob'].replace({'at_home':0, 'health':1, 'other':2, 'services':3, ' teacher':4}).astype('category')

In [12]:
df['Mjob'] = df['Mjob'].replace({'teacher':4}).astype('category')

In [13]:
df['Fjob'] = df['Fjob'].replace({'at_home':0, 'health':1, 'other':2, 'services':3, 'teacher':4}).astype('category')

In [14]:
df['reason'] = df['reason'].replace({'course':0, 'other':1, 'home':2, 'reputation':3}).astype('category')

In [15]:
df['guardian'] = df['guardian'].replace({'mother':0, 'father':1, 'other':2}).astype('category')

In [16]:
df.loc[:, 'schoolsup': 'romantic'] = df.loc[:, 'schoolsup': 'romantic'].replace({'no':0, 'yes':1}).astype('category')

In [17]:
df.loc[:, 'G1':'G3'] = df.loc[:, 'G1':'G3'].astype('category')

In [18]:
df

    school sex  age address famsize Pstatus  ... Walc health absences  G1  G2  G3
0        0   0   18       0       0       0  ...    1      3        6   5   6   6
1        0   0   17       0       0       1  ...    1      3        4   5   5   6
2        0   0   15       0       1       1  ...    3      3       10   7   8  10
3        0   0   15       0       0       1  ...    1      5        2  15  14  15
4        0   0   16       0       0       1  ...    2      5        4   6  10  10
..     ...  ..  ...     ...     ...     ...  ...  ...    ...      ...  ..  ..  ..
390      1   1   20       0       1       0  ...    5      4       11   9   9   9
391      1   1   17       0       1       1  ...    4      2        3  14  16  16
392      1   1   21       1       0       1  ...    3      3        3  10   8   7
393      1   1   18       1       1       1  ...    4      5        0  11  12  10
394      1   1   19       0       1       1  ...    3      5        5   8   9   9

[395 rows x 33 columns]

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    category
 1   sex         395 non-null    category
 2   age         395 non-null    int64
 3   address     395 non-null    category
 4   famsize     395 non-null    category
 5   Pstatus     395 non-null    category
 6   Medu        395 non-null    category
 7   Fedu        395 non-null    category
 8   Mjob        395 non-null    category
 9   Fjob        395 non-null    category
 10  reason      395 non-null    category
 11  guardian    395 non-null    category
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    category
 16  famsup      395 non-null    category
 17  paid        395 non-null    category
 18  activities  395 non-null    category
 19  nursery     395 non-null    category
 20  higher      395 non-null    category
 21  internet    395 non-null    category
 22  romantic    395 non-null    category
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    category
 31  G2          395 non-null    category
 32  G3          395 non-null    category
dtypes: category(22), int64(11)
memory usage: 47.1 KB

In [20]:
x_train = df.iloc[:int(len(df)*0.8), :-1]
y_train = df.iloc[:int(len(df)*0.8), -1]
x_valid = df.iloc[int(len(df)*0.8):, :-1]
y_valid = df.iloc[int(len(df)*0.8):, -1]

In [21]:
rf_model = RandomForestClassifier(n_estimators=70, n_jobs=-1, max_depth=3)

In [22]:
rf_model.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': 3,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 70,
 'n_jobs': -1,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [23]:
rf_model.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=3, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=70, n_jobs=-1,
                       oob_score=False, random_state=None, verbose=0,
                       warm_start=False)

In [24]:
prediction = rf_model.predict(x_valid)

In [25]:
accuracy_score(y_valid, prediction)

0.45569620253164556